<?php
$name = 'Ihor';
$age = 32;
$pi = 3.14;
$arr1 = ['alex','vova','tolya'];
$arr2 = [‘alex’, ‘vova’, ‘tolya’, [‘kostya’, ‘olya’]];
$arr3 = [‘alex’, ‘vova’, ‘tolya’, [‘kostya’, ‘olya’, [‘gosha’, mila]]] ;
$arr4 = [[‘alex’, ‘vova’, ‘tolya’], [‘kostya’, ‘olya’], [‘gosha’, mila]];
echo $name;
echo "\n" . '____________________' . "\n";
print $name;
echo "\n" . '____________________' . "\n";
print_r($name);
echo "\n" . '____________________' . "\n";
echo $age;
echo "\n" . '____________________' . "\n";
print $age;
echo "\n" . '____________________' . "\n";
print_r($age);
echo "\n" . '____________________' . "\n";
echo $pi;
echo "\n" . '____________________' . "\n";
print $pi;
echo "\n" . '____________________' . "\n";
print_r($pi);
echo "\n" . '____________________' . "\n";
echo $arr1;
echo "\n" . '____________________' . "\n";
print $arr1;
echo "\n" . '____________________' . "\n";
print_r($arr1);
echo "\n" . '____________________' . "\n";
echo $arr2;
echo "\n" . '____________________' . "\n";
print $arr2;
echo "\n" . '____________________' . "\n";
print_r($arr2);
echo "\n" . '____________________' . "\n";
echo $arr3;
echo "\n" . '____________________' . "\n";
print $arr3;
echo "\n" . '____________________' . "\n";
print_r($arr3);
echo "\n" . '____________________' . "\n";
echo $arr4;
echo "\n" . '____________________' . "\n";
print $arr4;
echo "\n" . '____________________' . "\n";
print_r($arr4 );
echo "\n" . '____________________' . "\n";
